export default {
  title: 'Search Tips - DeedStock.com',
  tips: [
    'Pls only input lower-case-letter',
    "Search by brand needs a prefix 'brand' and connected by '-', E.g. 'brand-champion', 'brand-comme-des-garcons', 'brand-adidas-x-raf-simons'",
    "Only search footwear needs a prefix or suffix 'footwear' and connected by '-', E.g. 'adidas-x-alexander-wang-footwear', 'footwear-nike-acg', 'footwear-y-3'",
    'Ignore the final dot in the name',
    "Sepical: 'jardon', 'converse', 'clae' to 'asics', 'g-shock'",
    "Sepical: 'womens-footwear' is for 'Nike Woman's' footwear, 'brand-medicom' is for 'Medicom Toy' etc."
  ],
  category: [
    '{ie',
    'adidas',
    'adidas x Alexander Wang',
    'adidas x Raf Simons',
    "adidas Women's",
    'Aimé Leon Dore',
    'Alltimers',
    'Alterior',
    'and wander',
    "Arc'teryx",
    'ASICS',
    'Babylon',
    'Baxter of California',
    'BEINGHUNTED.',
    'Born X Raised',
    'Brain Dead',
    'Bravo',
    'By Parra',
    'Carhartt WIP',
    'Casio',
    'Champion Reverse Weave',
    'Clae',
    'Clarks',
    'Cold World Frozen Goods',
    'COMME des GARÇONS',
    'Converse',
    'DSPTCH',
    "Explorer's Press",
    'Fronteer',
    'Fucking Awesome',
    'Gangster Doodles',
    'Garrett Leight',
    'G-SHOCK',
    'Garbstore',
    'Hibi',
    'HUF',
    'Hypebeast',
    'Ignored Prayers',
    'Incase',
    'Jason Markk',
    'Jordan',
    'Liberaiders',
    'Livestock',
    'LSD World Peace',
    'MAAPS',
    'Maharishi',
    'Malibu',
    'Manastash',
    'MAPLE',
    'Medicom Toy',
    'Medicom Fabrick',
    'Medicom Sync',
    'Metropolitan',
    'Mister Green',
    'New Balance',
    'Nike',
    'NikeLab',
    'Nike ACG',
    "Nike Women's",
    'Pleasures',
    'Porter',
    'Powers Supply',
    'Publications',
    'Puma',
    'Quiet Life',
    'Reebok',
    'RoToTo',
    'Saucony',
    'Stan Ray',
    'Suicoke',
    'Taikan',
    'The North Face',
    'Wood Wood',
    'Y-3'
  ]
}
