export default {
  title: 'Search Tips - SocialStatus.com',
  tips: [
    'Pls only input lower-case-letter',
    "Use '-' to replace space and symbols, E.g. 'COMME DES GARÇONS | PLAY' to 'comme-des-garcons-play', 'FXXKING RABBITS' to 'fxxking-rabbits'",
    "Replace last dot '.' into '-1', E.g. 'SYNC.' to 'sync-1'",
    "Sepical: 'DENIM BY VANQUISH & FRAGMENT' to 'denim-by', 'BILLIONAIRE BOYS CLUB' to 'bbc-black', 'NUDIE JEANS CO.' to 'nudie'",
    "Famous: 'jardon', 'converse', 'off-white', 'a-bathing-ape', 'kenzo', 'nike'"],
  category:
    [
      '3.1 PHILLIP LIM',
      'A.P.C.',
      'A BATHING APE',
      'ADIDAS',
      'ALMOST-ALWAYS',
      'AMBUSH',
      'ARIES',
      'BABYLON',
      'BE@RBRICK',
      'BILLIONAIRE BOYS CLUB',
      'BORN X RAISED',
      'BOW3RY',
      'BRANDBLACK',
      'CARROTS BY ANWAR CARROTS',
      'CENTRAL HIGH',
      'CHAMPION',
      'CHINATOWN MARKET',
      'COMMES DES GARCONS',
      'COMME DES GARÇONS | PLAY',
      'CONVERSE',
      'COURANT',
      'DENIM BY VANQUISH & FRAGMENT',
      'DIADORA',
      'FACETASM',
      'FOR THOSE WHO SIN',
      'FXXKING RABBITS',
      'HERON PRESTON',
      'HUMAN MADE',
      'I-D',
      'ICECREAM',
      'JASON MARKK',
      'JORDAN',
      'JUNGLES',
      'JUST DON',
      'JUUN.J',
      'KAPPA',
      'KARHU',
      'KENZO',
      'KNYEW',
      'KRINK',
      'LA CARRERA',
      'LUMIÈRES',
      'MIDNIGHT STUDIOS',
      'MODERN MAN',
      'MR.COMPLETELY',
      'N.D.G STUDIO',
      'NEIGHBORHOOD',
      'NIKE',
      'NUDIE JEANS CO.',
      'OFF-WHITE',
      'PASADENA LEISURE CLUB',
      'PATERSON',
      'PERKS AND MINI',
      'PLANES',
      'PLEASURES',
      'POLAROID',
      'PUMA',
      'PURPLE',
      'REEBOK',
      'ROKIT',
      'SANDALBOYZ',
      'SECRID',
      'SERENADE',
      'SOCIAL STATUS',
      'SURF IS DEAD',
      'SYNC.',
      'TIMBERLAND',
      'UNITED STANDARD',
      'UPWW',
      'VANS',
      'VITAL MATERIAL'
    ]
}
